### ISSUE TITLE
You have any sample design?

### ISSUE THREAD

**Issue by jefferson-william** [heavymery/grunt-require-rev#4]
I made this package work in parts in my design. After numerous tests and ways of doing, did not work 100%.

I wonder if there is a project where I can base myself?

**Comment by heavymery** [comment]
@jefferson-william Do you want sample project or files for `grunt-require-rev`?

You can fine usage examples on [README](https://github.com/heavymery/grunt-require-rev#usage-examples) and `test/fixture/`.

- Example for [default options](https://github.com/heavymery/grunt-require-rev#default-options)
=> https://github.com/heavymery/grunt-require-rev/tree/master/test/fixtures/default_options
- Example for [custom options](https://github.com/heavymery/grunt-require-rev#custom-options)
=> https://github.com/heavymery/grunt-require-rev/tree/master/test/fixtures/custom_options

And expected result is located on `test/expected/`.
https://github.com/heavymery/grunt-require-rev/tree/master/test/expected
