### ISSUE TITLE
File name replaced wrong

### ISSUE THREAD

**Issue by jefferson-william** [heavymery/grunt-require-rev#6]
@heavymery In my tests, had two files with similar names. The first was jquery-migrate.js and jquery.js.

As I understand it, the first jquery-migrate.js file had its name changed, but according to my RequireJS configuration file, was to be jquery.js only.

Example:

**Before**

```
- app
    - bower_components
        - jquery
            - jquery-migrate.js
            - jquery.js
    - scripts
        - bootstrap.js
        - main.js
```

app/scripts/bootstrap.js

``` js
'use strict';
require.config({
    baseUrl: '/scripts',
    paths: {
        'main': 'main',
        'jquery': '../bower_components/jquery/jquery'
    }
});
require([
    'jquery',
    'main'
], function(jquery, main) {
    $('body').html('Hello!');
});
```

**After**

```
- app
    - bower_components
        - jquery
            - 996f42cf.jquery-migrate.js // Wrong
            - jquery.js // Right
    - scripts
        - bootstrap.js
        - eeedbd79.main.js
```

app/scripts/bootstrap.js

``` js
'use strict';
require.config({
    baseUrl: '/scripts',
    paths: {
        'eeedbd79.main': 'eeedbd79.main',
        'jquery': '../bower_components/jquery/jquery'
    }
});
require([
    'jquery',
    'eeedbd79.main'
], function(jquery, main) {
    $('body').html('Hello!');
});
```

Beyond what I mentioned above, an error appears in the terminal:

```
Running "requireRev: dist" (requireRev) task
Warning: Can not read property 'source' of undefined Use --force to continue.
Aborted due to warnings.
```

**Comment by heavymery** [comment]
@jefferson-william Let me show `requireRev` configuration on Gruntfile.js.

**Comment by jefferson-william** [comment]
@heavymery Sorry, but I wiggled the file and do not know but as it was.

You could do some testing there according to my example?

I'm trying to use this package the days and none of the ways I tried to work perfectly.

It's a shame I did not find out exactly how was the Gruntfile.js file of this example. But if you can help me just by looking at the above information I thank you. Otherwise I will understand.

**Comment by heavymery** [comment]
@jefferson-william Sorry for late response. I was able to reproduce this bug. Maybe, your `requireRev` configuration was like below. right?

```
    requireRev: {
      dist: {
        expand: true,
        cwd: 'app',
        src: [
          'scripts/**/*.js',
          'bower_components/**/*.js'
        ]
      },
```

This issue is bug. But purpose of `requireRev` is revisioning **requirejs dependency** files. So, configuration should be like below.

```
    requireRev: {
      dist: {
        expand: true,
        cwd: 'app',
        src: [
          'scripts/**/*.js'
        ]
      },
```

**Comment by heavymery** [comment]
@jefferson-william And If your project has no need to deploy multiple requireJS dependency files, I suggest to use [grunt-contrib-requirejs](https://github.com/gruntjs/). 

This package will help you to optimize multiple requireJS dependency files to one js file like below.

**Before**

``` js
// hello.js
define(function(){return "hello";});

// world.js
define(function(){return "world";});

// project.js
require(['hello', 'world'], function(hello, world) {
  console.log(hello,world);
});
```

**After**

``` js
// project-optimized.js
define("hello",[],function(){return"hello"}),
define("world",[],function(){return"world"}),
require(["hello","world"],function(e,t){console.log(e,t)}),define("project",function(){});
```
